game_time: 100
robot_time: 25
log_level: 'DEBUG'

charging_time: 5
charging_amount: 25

points:
  good: 1
  bad: -2

fields_names:
  - game_field
  - blue_plastic # blue
  - blue_glass # green
  - red_plastic # red
  - red_glass # black

objects:
  plastic:
    - 30 #red
  glass:
    - 29 # green
  shells:
    - 39 # blue

robots:
  0:  Ocvrte antenice
  5:  GaSa Dynamics
  9:  Works on Our Machine 
  10: Leščurji
  12: los programadores
  14: Ibržnik
  18: Unicode Abuse

