game_time: 100
robot_time: 25
log_level: 'DEBUG'

charging_time: 5
charging_amount: 25

points:
  good: 1
  bad: -2

fields_names:
  - game_field
  - blue_basket
  - red_basket
  - charging_station_1
  - charging_station_2

objects:
  good_ore:
    - 36
    - 39
    - 40
    - 41
    - 42
    - 43
    - 47
  bad_ore:
    - 29
    - 30
    - 32
    - 35

robots:
  0:  Hansformers
  5:  Unicode Abuse
  9:  Gold Diggers
  10: Bumblebee
  12: PeΨ
  14: ocvrti čipi
  18: Lolek in Bolek
  19: Sussy Bakas
  22: LASPP
  24: VimEscapees

